import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import StoreProvider from "../lib/StoreProvider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Modal from "@/components/ui/NewWorkspaceModal";
import { ReactQueryProvider } from "./react-query-proider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-background text-text"}>
        <ReactQueryProvider>
          <StoreProvider >
            <Sidebar />
            <Header />
            <main className="h-[calc(100vh-48px)] w-screen sm:w-[calc(100vw-256px)] sm:ml-64">
              {children}
            </main>
            <Modal />
          </StoreProvider>
        </ReactQueryProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
