import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import StoreProvider from "../lib/StoreProvider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import NewWorkapces from "@/components/ui/NewWorkspaceModal";
import NewBoardModal from "@/components/ui/NewBoardModal";
import { ReactQueryProvider } from "./react-query-proider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-background text-text"}>
        <ReactQueryProvider>
          <StoreProvider >
            {children}
            <NewWorkapces />
            <NewBoardModal />
          </StoreProvider>
        </ReactQueryProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
