import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID!}>
        <body className={inter.className + " bg-background text-text"}>
          <Sidebar />
          <Header />
          <main className="h-[calc(100vh-80px)] w-screen sm:w-[calc(100vw-256px)] p-4 sm:ml-64 bg-white">
            {children}
          </main>
        </body>
      </GoogleOAuthProvider>
    </html>
  );
}
